---
- name: Set download paths
  ansible.builtin.set_fact:
    download_url: "{{ release_url }}/{{ release_version }}"
    download_file: "plik-{{ release_version }}-linux-{{ architecture }}.tar.gz"

- name: Set install base directory
  ansible.builtin.set_fact:
    download_file_base: "{{ download_file | splitext | first | splitext | first }}"

- name: Check if package is downloaded
  command: test -e {{ install_dest }}/{{ download_file }}
  ignore_errors: True
  register: package_exists

- name: Fetch software package
  ansible.builtin.get_url:
    url: "{{ download_url }}/{{ download_file }}"
    dest: "{{ install_dest }}/"
    mode: "644"
    checksum: "sha256:{{ download_url }}/sha256sum.txt"
  when: package_exists.rc != 0

- name: Untar package
  ansible.builtin.unarchive:
    src: "{{ install_dest }}/{{ download_file }}"
    dest: "{{ install_dest }}/"
    extra_opts: ['-z']

- name: Copy configuration file
  ansible.builtin.template:
    src: templates/plikd.cfg.j2
    dest: "{{ install_dest }}/{{ download_file_base }}/server"
  notify:
    - Start Plik server
